services:
  utnDB:
    image: postgres:13-alpine
    container_name: database
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=utn_admin
      - POSTGRES_PASSWORD=utn_password
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=test.utn.mongo@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=12345
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    ports:
      - 8080:80
    depends_on:
      - utnDB